baseURL = 'https://nginx.org'
languageCode = 'en-us'
title = 'Example Site'
enableGitInfo = true


[module]
[[module.imports]]
  path="github.com/nginxinc/nginx-hugo-theme/v2"


[caches]
[caches.modules]
maxAge = -1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      guessSyntax = true
      noClasses = false

[params]
  github_repo = "https://github.com/nginxinc/nginx-hugo-theme"
  github_subdir = "exampleSite"
  enable_last_modified = true
  coveo_search_redirect = "/search.html"
  [params.featureFlags]
    disable_coveo = true
    disable_qualtrics = true
